### ISSUE TITLE
Support for Symfony 6.0

### ISSUE THREAD

**Issue by dzanfardino** [facile-it/facile-coding-standard#38]
Symfony 6.0 got released, and since version 3.4.0 PHP-CS-FIXER supports it. 
I'm not sure this would represent a major version bump in the package though.

**Comment by Jean85** [comment]
Supporting the newer version shouldn't be an issue, we just need to widen our version constraint about `symfony/console`. We're out of luck in terms of testing in our CI though, thanks to https://github.com/composer/composer/issues/10321.

We can probably try to remove `composer/composer` as a dependency at least in a single CI job to test it, otherwise we can't release the compatibility "blindly".

**Comment by dzanfardino** [comment]
Done in #39
